import("//build/templates/build_template.gni")
build_rust("cortex_m") {
  crate_type = "rlib"
  sources = [ "src/lib.rs" ]
  edition = "2018"

  deps = [
    "//external/bare-metal/v0.2.5:bare_metal",
    "//external/bitfield/v0.13.2:bitfield",
    "//external/embedded-hal/v0.2.7:embedded_hal",
    "//external/volatile-register/v0.2.2:volatile_register",
  ]

  features = [ "inline-asm" ]

  rustflags = [ "--cap-lints=allow" ]

  lib_path = rebase_path("bin")
  if (board == "qemu_mps2_an385") {
    rustflags += [
      "-Clink-arg=$lib_path/thumbv7m-none-eabi",
      "--cfg",
      "cortex_m",
      "--cfg",
      "armv7m",
    ]
  } else if (board == "qemu_mps3_an547" || board == "raspberry_pico2_cortexm") {
    rustflags += [
      "-Clink-arg=$lib_path/thumbv8m.main-none-eabihf",
      "--cfg",
      "cortex_m",
      "--cfg",
      "armv8m",
      "--cfg",
      "armv8m_main",
      "--cfg",
      "has_fpu",
    ]
  } else {
    not_needed([ lib_path ])
  }
}
