import("//build/templates/build_template.gni")

build_rust("cortex_m") {
  crate_type = "rlib"
  sources = [ "src/lib.rs" ]
  edition = "2018"

  deps = [
    "//external/bare-metal/v0.2.5:bare_metal",
    "//external/bitfield/v0.13.2:bitfield",
    "//external/embedded-hal/v0.2.7:embedded_hal",
    "//external/volatile-register/v0.2.2:volatile_register",
  ]
  features = [ "inline-asm" ]
  configs += [ "//build/boards/${board}:kernel_config" ]
}
